### ISSUE TITLE
Subfolders break the draft and post actions

### ISSUE THREAD

**Issue by erbridge** [23maverick23/sublime-jekyll#30]
I have my posts organized in subdirectories within the `_posts` and `_drafts` directories, and running the open commands or the promote command raises an `IndexError` and does nothing.

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 526, in run_
    return self.run()
  File "jekyll in /home/felix/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 422, in run
  File "jekyll in /home/felix/.config/sublime-text-3/Installed Packages/Jekyll.sublime-package", line 422, in <lambda>
IndexError: list index out of range
```

**Comment by 23maverick23** [comment]
@erbridge Thanks for sending this over. I'm happy to take a look at a fix, but subdirectories in `_posts` and `_drafts` aren't officially supported by Jekyll I don't believe. Are you using a plugin to generate your posts?

I don't really think it makes sense to support something that is non-standard or "custom" in Jekyll.

**Comment by erbridge** [comment]
I don't know if they're intentionally supported, but subdirectories worked out of the box for me.

**Comment by 23maverick23** [comment]
Interesting - is there any way you can share your setup or config so that I can take a look? I'd love to support this if it's something I can test for :wink: 

I can't find anything in my quick research that suggests this is supported intentially. There is an [SO article][stackoverflow] that talks about folders, which links to the [Jekyll front matter][jekyll] docs. However, I did see [this blog post][blog] which suggested that subdirectories in `_posts` are supported, they just don't do anything (e.g. they don't create categories or tags automatically).

[stackoverflow]: http://stackoverflow.com/a/15279405
[jekyll]: http://jekyllrb.com/docs/frontmatter/#predefined-global-variables
[blog]: https://divshot.com/blog/web-development/advanced-jekyll-features/#custom-post-types

**Comment by erbridge** [comment]
https://github.com/erbridge/erbridge.github.io is the site I'm working on (run `bundle install` for the dependencies). As you say, the subdirectories don't do anything useful except organize the posts in the file hierarchy.

**Comment by 23maverick23** [comment]
Thanks. I'll take a look and add support for posts in sub-directories.

**Comment by 23maverick23** [comment]
@erbridge Let me know if this fix addresses the bug you were seeing. I tested quickly with multiple levels of subdirectories inside the `_drafts` folder and it seemed to work.

I also added support for subdirectories in the _"Promote draft to post"_ command (it finds your `_posts` directory and copies the entire subdirectory tree from `_drafts`, which seems to make the most amount of sense).

**Comment by erbridge** [comment]
It works. Thanks!
