### ISSUE TITLE
Haml support

### ISSUE THREAD

**Issue by oprema** [23maverick23/sublime-jekyll#35]
Hi there,
I wished to have haml syntax support for this extension. Is this already in planing?

**Comment by 23maverick23** [comment]
Hey @oprema - thanks for using the plugin! I don't have any plans to support Haml since it's not an [official language](http://jekyllrb.com/docs/posts/#the-posts-folder) that Jekyll supports. However, if someone wanted to send a pull request with support for it I'll gladly take a look and consider it for a future release!

**Comment by 23maverick23** [comment]
Closing due to lack of feedback.
