### ISSUE TITLE
Is it possible to change default syntax highlight?

### ISSUE THREAD

**Issue by rudvfaden** [23maverick23/sublime-jekyll#36]
Thanks for a great plugin. 

I really like the MarkdownExtended syntax highlight for markdown. Is it possible make this defualt?

**Comment by 23maverick23** [comment]
Thanks @rudvfaden 

Have you tried using the feature to "Open all with current extension as..."? I'm not sure if that works - the plugin as-is attempts to set the correct custom syntax file for you using the syntaxes provided - [L70-90](https://github.com/23maverick23/sublime-jekyll/blob/master/jekyll.py#L70-90).

`View -> Syntax -> Open all with current extension as... ->[your syntax choice]`

Let me know if that solves the problem - otherwise I'll look and see if we could enhance it to support more flexible syntaxes.

**Comment by rudvfaden** [comment]
It dos not work. When creating the post it is still using the default syntax highlight. I have to open and close the file for it to change the syntax.

**Comment by 23maverick23** [comment]
I may need to re-write how I detect and apply syntaxes, which could take some time.

I'll put this on my backlog and see if we can't support it in the next major release.
