### ISSUE TITLE
It it possible to add the date and time as information on the post?

### ISSUE THREAD

**Issue by aurelkurtula** [23maverick23/sublime-jekyll#37]
Hi

Is there a way to get the date information as part of the post's data, similar as the sample bellow (the date part)?

```
---
layout: post
title: "Some title"
date: 2015-05-19 03:32:35 +0100
categories:[]
tags:[]
---
```

Thanks

**Comment by 23maverick23** [comment]
We don't add this to the default front matter, since it's typically redundant with the date in the post title.

If you want to have the date tag for more precise post ordering, you could add it as a `default_post_extras` key, and then use the available command `Jekyll: Insert current datetime` to add the date (it's available from the command palette or the right-click context menu). You'll also likely want to modify the standard `insert_datetime_format` setting to match the output you provided in your post.

```json
// Jekyll.sublime-settings
"default_post_extras": {"date": ""},
"insert_datetime_format": "%Y-%m-%d %H:%M:%S %z"
```
