### ISSUE TITLE
Can't Remove Key from Front-Matter

### ISSUE THREAD

**Issue by splttingatms** [23maverick23/sublime-jekyll#53]
Assigning null values to "default_post_categories", "default_post_tags", and "default_post_published" in sublime project setting does not remove the key from YAML front-matter as described in the documentation.

> // To remove this key from your front-matter completely, pass a value of `null`.
> "default_post_categories": null,

Is there a trick to removing the key from post template?

**Comment by splttingatms** [comment]
I believe the issue is that there is no null check in get_settings. Should be:
```
def get_setting(view, key, default=None):
        s = settings.get('Jekyll').get(key)
        if s and s != "null":
            return s
        else:
            pass
```

**Comment by 23maverick23** [comment]
Hey @splttingatms ! Thanks for using the plugin and providing feedback.

The value of `null` is actually being used in the `.sublime-settings` file (which is really just a `.json` file), and is automatically converted to `None` when loaded into ST to comply with Python "null" type values. You can run a quick test to see how this works in your terminal or IDLE:

```python
import json
data = '{"default_post_categories": null}'
json.loads(data)
>>> {u'default_post_categories': None}
```

I just ran a quick test on my end and it seems to work for me on ST3. Can you confirm a few things:

1. What OS and version of ST are you running?
2. Are there any errors printed to your ST console ( <kbd>CTRL</kbd>+<kbd>~</kbd> )?
3. Where are you storing your Jekyll settings (should be under _Package Settings > Jekyll > Settings - User_)?

**Comment by splttingatms** [comment]
Hey thanks for the quick response.

1. Running ST3 Stable Channel Build 3083 on Windows 10 Pro 64-bit
2. No errors in ST console when opening project. Running the example json test also works as you described.
3. Project settings file "jekyll-demo.sublime-project" is stored in the root directory of the project. Could that be an issue?

Contents of jekyll-demo.sublime-project
```
{
	"folders":
 	[
		{
			"follow_symlinks": true,
			"path": "D:\\Projects\\jekyll-demo"
		}
	],

	"settings":
	{
		"Jekyll":
		{
			"posts_path": "D:\\Projects\\jekyll-demo\\_posts",
			"drafts_path": "D:\\Projects\\jekyll-demo\\_drafts",
			"default_post_layout": "post",
			"default_post_categories": null,
			"default_post_tags": null,
			"default_post_published": null,
			"default_post_extras": null,
		}
	}
}
```

Output from running "Jekyll: New Post" snippet
```
---
layout: post
title: test
categories: []
tags: []
published: True

---

```

**Comment by 23maverick23** [comment]
Ok - I setup my project to match yours and I'm now seeing the same results. Basically - I've coded the plugin to lookup project settings first and fall back to user settings (which is the correct way to support optional project overrides). The issue is that a missing key and a `None` key are treated the same in my implementation (which is a design oversight on my end). The next version of the plugin I'm working on will support YAML front-matter templates (rather than default keys). This will allow for infinite customization of your posts and won't require you to use overrides at all.

So...I'm wondering if a suitable workaround for you for now is to override your user `Jekyll.sublime-settings` file to have `null` for all defaults. Then, each time you create a project, you can decide if you want to override them. I tested this and it seems to give the desired results.

Let me know!
